import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db, schema } from "./db";

/**
 * Better Auth instance: email + password, sessions in an httpOnly cookie.
 * Storage is Postgres through the Drizzle adapter (user/session/account/
 * verification tables from `db/auth-schema.ts`, generated by the CLI).
 * Secret and base URL come from BETTER_AUTH_SECRET / BETTER_AUTH_URL.
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, { provider: "pg", schema }),
  emailAndPassword: { enabled: true },
  // Vercel preview deployments live on hosts other than BETTER_AUTH_URL —
  // without this their origin fails the CSRF check.
  trustedOrigins: ["https://*.vercel.app"],
});
