/**
 * Single assembly point for the DB schema: Better Auth tables (generated by the
 * CLI — do not edit `auth-schema.ts` by hand) plus our application tables.
 */
export * from "./auth-schema";
export * from "./favorites-schema";
